project:
  type: website
  render:
    - units/intro.qmd
    - prep.qmd
    - index.qmd

website:
  site-url: https://paciorek.github.io/r-voleon-2025
  sidebar:
    style: docked
    title: "Voleon R Bootcamp"
    tools:
      - icon: github
        href: https://github.com/paciorek/r-voleon-2025
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: prep.qmd
        text: Preparation
      - section: "Modules"
        contents:
          - href: units/intro.qmd
            text: Basic Introduction (Module "0")
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



