project:
  type: website
  render:
    - units/intro.qmd
    - units/data.qmd
    - units/calculation.qmd
    - units/programming.qmd
    - units/tidyverse.qmd
    - units/ggplot.qmd
    - units/analysis.qmd
    - units/topics.qmd

website:
  site-url: https://paciorek.github.io/r-voleon-2025
  sidebar:
    style: docked
    title: "Voleon R Bootcamp"
    tools:
      - icon: github
        href: https://github.com/paciorek/r-voleon-2025
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: prep.qmd
        text: Preparation
      - section: "Modules (a partial set)"
        contents:
          - href: units/intro.qmd
            text: Basic Introduction (Module "0")
          - href: units/data.qmd
            text: Data Structures
          - href: units/calculation.qmd
            text: Calculation
          - href: units/programming.qmd
            text: Programming
          - href: units/tidyverse.qmd
            text: Data Wrangling
          - href: units/ggplot.qmd
            text: Plotting (ggplot)
         

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



